-- Rollback-only, two real-account identities with disposable fixture profiles/content.
begin;
do $$
declare cf uuid; cu uuid; af uuid; au uuid; cp uuid; ap uuid; programme uuid; version_uuid uuid; copied uuid; duplicate_id uuid; report_id uuid; assessment uuid; test_id uuid; content jsonb; plan_before jsonb; result jsonb; denied boolean; row record;
begin
 select id,owner_user_id into cf,cu from public.families order by created_at limit 1;
 select id,owner_user_id into af,au from public.families where owner_user_id<>cu order by created_at limit 1;
 if af is null then raise exception 'Two account families required'; end if;
 insert into public.profiles(family_id,name) values(cf,'Community creator fixture') returning id into cp;
 insert into public.profiles(family_id,name) values(af,'Community member fixture') returning id into ap;
 insert into private.creator_reviewers(user_id) values(cu) on conflict do nothing;
 insert into public.assessment_templates(family_id,name) values(cf,'Community checkpoint fixture') returning id into assessment;
 insert into public.tests(family_id,name) values(cf,'Community test fixture') returning id into test_id;
 insert into public.assessment_template_tests(family_id,assessment_template_id,test_id,position) values(cf,assessment,test_id,1);
 content:='{"version":5,"activityTypes":[],"blocksByWeekday":{"Mon":[],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]},"program":{"schemaVersion":1,"name":"Community fixture","description":"","startDate":"2026-10-05","completionMode":"repeat","phases":[{"id":"phase","name":"Build","focus":"","weeks":[{"id":"week","name":"Week 1","focus":"","blocksByWeekday":{"Mon":[],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]}}],"assessments":[]}]}}';
 content:=jsonb_set(content,'{program,phases,0,assessments}',jsonb_build_array(jsonb_build_object('id','checkpoint','label','Before','timing','before','assessmentTemplateId',assessment)));
 perform set_config('request.jwt.claim.sub',cu::text,true);
 execute 'set local role authenticated';
 perform public.creator_save_profile(cp,'{"display_name":"Community coach fixture","published":true}');
 select * into row from public.training_program_save(null,cf,cp,'Community fixture','Fixture description','Speed','Football','beginner','all_ages','{}','{}','coach',content,'Initial fixture');
 programme:=row.program_id; version_uuid:=row.version_id;
 perform public.training_program_publish_free(programme);
 denied:=false; begin perform public.community_vote(cp,programme,true,version_uuid,'Speed'); exception when others then denied:=true; end;
 if not denied then raise exception 'Self-promotion vote allowed'; end if;
 perform set_config('request.jwt.claim.sub',au::text,true);
 select plan_json into plan_before from public.profiles where id=ap;
 perform public.community_bookmark(ap,programme,true);
 denied:=false; begin perform public.community_bookmark(cp,programme,true); exception when others then denied:=true; end;
 if not denied then raise exception 'Foreign bookmark written'; end if;
 perform public.community_vote(ap,programme,true,version_uuid,'Speed');
 perform public.community_vote(ap,programme,false,version_uuid,'Speed');
 result:=public.community_context(ap);
 if not exists(select 1 from jsonb_array_elements(result->'programmes') s where s->>'program_id'=programme::text and (s->>'helpful')::integer=0 and (s->>'not_helpful')::integer=1 and s->>'my_vote'='false') then raise exception 'One-vote replacement or counts failed'; end if;
 denied:=false; begin perform public.community_vote(ap,programme,true,version_uuid,'Wrong purpose'); exception when others then denied:=true; end;
 if not denied then raise exception 'Stale purpose vote allowed'; end if;
 copied:=public.community_copy(ap,programme,version_uuid,'Personal fixture copy');
 if (select plan_json from public.profiles where id=ap) is distinct from plan_before then raise exception 'Bookmark/vote/copy changed active plan'; end if;
 if not exists(select 1 from public.training_programs where id=copied and owner_family_id=af and marketplace_status='not_listed' and community_origin_program_id=programme) then raise exception 'Private copy has incorrect ownership or origin'; end if;
 if not exists(select 1 from public.training_program_versions where program_id=copied and content_json #>> '{program,phases,0,assessments,0,assessmentDefinition,template,name}'='Community checkpoint fixture') then raise exception 'Community Assessment snapshot was lost'; end if;
 select * into row from public.training_program_copy_version(copied,(select current_version_id from public.training_programs where id=copied),true,'Duplicate fixture copy','Private duplicate',null);
 duplicate_id:=row.program_id;
 denied:=false; begin perform public.training_program_publish_free(duplicate_id); exception when others then denied:=true; end;
 if not denied then raise exception 'Duplicate laundered Community origin'; end if;
 denied:=false; begin perform public.community_set_copy_permission(programme,false); exception when others then denied:=true; end;
 if not denied then raise exception 'Foreign copy permission edited'; end if;
 report_id:=public.community_report(ap,programme,null,'safety','Please check the fixture training instructions.');
 denied:=false; begin perform public.community_report(ap,programme,null,'safety','Duplicate report fixture.'); exception when others then denied:=true; end;
 if not denied then raise exception 'Duplicate open report allowed'; end if;
 denied:=false; begin perform public.community_reports(); exception when others then denied:=true; end;
 if not denied then raise exception 'Member read moderation queue'; end if;
 denied:=false; begin perform public.community_review_report(report_id,'hide','Member cannot moderate'); exception when others then denied:=true; end;
 if not denied then raise exception 'Member moderated report'; end if;
 perform set_config('request.jwt.claim.sub',cu::text,true);
 perform public.community_set_copy_permission(programme,false);
 perform set_config('request.jwt.claim.sub',au::text,true);
 denied:=false; begin perform public.community_copy(ap,programme,version_uuid,'Forbidden copy'); exception when others then denied:=true; end;
 if not denied then raise exception 'Copy permission bypassed'; end if;
 perform public.training_program_apply_accessible(programme,ap,'2026-10-05','repeat','add',null);
 if not exists(select 1 from public.training_program_checkpoints where profile_id=ap and source_key=programme::text and assignment_id is null and active) then raise exception 'Library Assessment checkpoint was not scheduled independently of assignments'; end if;
 denied:=false; begin perform public.training_program_save(null,af,ap,'Bypass fixture','','Speed','','all_levels','all_ages','{}','{}','community',(select content_json from public.training_program_versions where id=version_uuid),'Unchanged content'); exception when others then denied:=true; end;
 if not denied then raise exception 'Active-plan save bypassed no-copy permission'; end if;
 denied:=false; begin perform public.training_program_apply_accessible(copied,ap,'2026-10-05','repeat','add',null); exception when others then denied:=true; end;
 if not denied then raise exception 'Second add-on allowed'; end if;
 perform set_config('request.jwt.claim.sub',cu::text,true);
 perform public.community_review_report(report_id,'hide','Hidden pending a review of the training instructions.');
 denied:=false; begin perform public.training_program_publish_free(programme); exception when others then denied:=true; end;
 if not denied then raise exception 'Publishing hold bypassed'; end if;
 if exists(select 1 from public.training_program_list_community() where id=programme) then raise exception 'Hidden programme discoverable'; end if;
 perform set_config('request.jwt.claim.sub',au::text,true);
 result:=public.community_context(ap);
 if not exists(select 1 from jsonb_array_elements(result->'bookmarks') b where b->>'program_id'=programme::text and b->>'available'='false') then raise exception 'Unavailable bookmark was lost'; end if;
 if not exists(select 1 from public.profiles where id=ap and plan_json #>> '{meta,programAddOns,0,programId}'=programme::text) then raise exception 'Moderation deleted adopted programme'; end if;
 perform public.community_bookmark(ap,programme,false);
 perform set_config('request.jwt.claim.sub',cu::text,true);
 perform public.community_review_report(report_id,'restore','Reviewed and ready for the owner to publish again.');
 perform public.training_program_publish_free(programme);
 execute 'reset role';
 update public.training_programs set purpose='Mobility' where id=programme;
 execute 'set local role authenticated';
 perform set_config('request.jwt.claim.sub',au::text,true);
 result:=public.community_context(ap);
 if exists(select 1 from jsonb_array_elements(result->'programmes') s where s->>'program_id'=programme::text and ((s->>'helpful')::integer<>0 or (s->>'not_helpful')::integer<>0)) then raise exception 'Old-purpose feedback counted'; end if;
 perform public.community_vote(ap,programme,true,version_uuid,'Mobility');
 perform set_config('request.jwt.claim.sub',cu::text,true);
 select * into row from public.training_program_save(programme,cf,cp,'Community fixture','Fixture description','Mobility','Football','beginner','all_ages','{}','{}','coach',content,'Updated fixture');
 perform set_config('request.jwt.claim.sub',au::text,true);
 result:=public.community_context(ap);
 if exists(select 1 from jsonb_array_elements(result->'programmes') s where s->>'program_id'=programme::text and ((s->>'helpful')::integer<>0 or s->>'my_vote' is not null)) then raise exception 'Old-version feedback counted'; end if;
 denied:=false; begin perform public.community_vote(ap,programme,true,version_uuid,'Mobility'); exception when others then denied:=true; end;
 if not denied then raise exception 'Stale-version vote allowed'; end if;
 report_id:=public.community_report(ap,null,cp,'misleading','Please check this creator credential claim.');
 perform set_config('request.jwt.claim.sub',cu::text,true);
 perform public.community_review_report(report_id,'hide','Creator claim is paused pending evidence review.');
 denied:=false; begin perform public.creator_save_profile(cp,'{"display_name":"Community coach fixture","published":true}'); exception when others then denied:=true; end;
 if not denied then raise exception 'Creator bio hold bypassed'; end if;
 denied:=false; begin perform public.training_program_publish_free(programme); exception when others then denied:=true; end;
 if not denied then raise exception 'Creator programme hold bypassed'; end if;
 perform public.community_review_report(report_id,'restore','Evidence checked; owner may publish again.');
 execute 'reset role';
 if has_function_privilege('anon','public.community_context(uuid)','EXECUTE') or has_table_privilege('authenticated','private.community_reports','SELECT') or has_table_privilege('authenticated','private.community_votes','INSERT') then raise exception 'Private data/API privilege leak'; end if;
 if not exists(select 1 from private.community_report_actions where note='Evidence checked; owner may publish again.') then raise exception 'Decision audit missing'; end if;
end $$;
select 'Community bookmarks, copy permissions, Assessment snapshots, vote revisions, report privacy, publishing holds, retained adoption and add-on limit passed' as result;
rollback;
