begin;
do $$
declare cf uuid; cu uuid; af uuid; au uuid; cp uuid; ap uuid; programme uuid; req uuid; row public.training_program_creators; details jsonb; denied boolean; file text; request_count integer; version_uuid uuid; content jsonb;
begin
 select id,owner_user_id into cf,cu from public.families order by created_at limit 1;
 select id,owner_user_id into af,au from public.families where owner_user_id<>cu order by created_at limit 1;
 if af is null then raise exception 'Two account families required'; end if;
 insert into public.profiles(family_id,name) values(cf,'Creator fixture') returning id into cp;
 insert into public.profiles(family_id,name) values(af,'Reviewer fixture') returning id into ap;
 insert into private.creator_reviewers(user_id) values(au) on conflict do nothing;
 details:='{"display_name":"Creator fixture","headline":"Youth coach","bio":"Training background","experience":"10 years coaching","years_experience":10,"role":"coach","categories":["Youth training"],"tags":["Football"],"qualifications":[{"name":"Coach certificate","issuer":"Fixture awarding body","reference_url":"https://example.org/register"}],"published":true,"verified_revision":1,"verified_at":"2026-01-01"}';
 content:='{"version":5,"activityTypes":[],"blocksByWeekday":{"Mon":[],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]},"program":{"schemaVersion":1,"name":"Creator plan","description":"","startDate":"2026-10-05","completionMode":"repeat","phases":[{"id":"phase","name":"Build","focus":"","weeks":[{"id":"week","name":"Week 1","focus":"","blocksByWeekday":{"Mon":[],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]}}],"assessments":[]}]}}';
 insert into public.training_programs(owner_family_id,creator_profile_id,title,access_model,marketplace_status,credentials_verified) values(cf,cp,'Creator programme fixture','free','published',true) returning id into programme;
 insert into public.training_program_versions(program_id,version_no,content_json,created_by_family_id) values(programme,1,content,cf) returning id into version_uuid;
 update public.training_programs set current_version_id=version_uuid where id=programme;
 perform set_config('request.jwt.claim.sub',cu::text,true);
 execute 'set local role authenticated';
 row:=public.creator_save_profile(cp,details);
 if row.verified_at is not null then raise exception 'Creator self-awarded badge'; end if;
 if not exists(select 1 from public.training_program_list_community() where id=programme and creator_id=cp and creator_name='Creator fixture' and not credentials_verified) then raise exception 'Catalogue trusted old programme badge or lost creator identity'; end if;
 denied:=false; begin perform public.creator_save_profile(ap,details); exception when others then denied:=true; end;
 if not denied then raise exception 'Foreign profile edited'; end if;
 denied:=false; begin update public.training_program_creators set verified_at=now() where id=cp; exception when others then denied:=true; end;
 if not denied then raise exception 'Direct verification update enabled'; end if;
 execute 'reset role';
 file:=cp::text||'/evidence/certificate.pdf';
 insert into storage.objects(bucket_id,name) values('creator-evidence',file);
 execute 'set local role authenticated';
 req:=public.creator_submit_verification(cp,'Please check this issuing-body reference and my certificate.',array[file]);
 denied:=false; begin perform public.creator_submit_verification(cp,'Another pending request',array[file]); exception when others then denied:=true; end;
 if not denied then raise exception 'Multiple pending requests allowed'; end if;
 denied:=false; begin perform public.creator_review_verification(req,'approved','Verified against fixture body'); exception when others then denied:=true; end;
 if not denied then raise exception 'Non-reviewer approved request'; end if;
 if (select count(*) from public.creator_verification_requests(cp))<>1 then raise exception 'Owner cannot read status'; end if;
 perform set_config('request.jwt.claim.sub',au::text,true);
 if not exists(select 1 from public.training_program_creators where id=cp) then raise exception 'Published bio unavailable'; end if;
 if not exists(select 1 from storage.objects where bucket_id='creator-evidence' and name=file) then raise exception 'Reviewer cannot read submitted evidence'; end if;
 if not public.creator_review_verification(req,'approved','Identity and certificate checked with the issuing body.') then raise exception 'Review failed'; end if;
 if not exists(select 1 from public.training_program_creators where id=cp and verified_revision=credential_revision and verified_at is not null) then raise exception 'Approved badge not visible'; end if;
 if not exists(select 1 from public.training_program_preview_community(programme) where creator_id=cp and credentials_verified) then raise exception 'Preview lost verified creator'; end if;
 perform public.creator_save_profile(ap,details||'{"display_name":"Reviewer fixture"}');
 req:=public.creator_submit_verification(ap,'Please verify my own qualifications.','{}');
 denied:=false; begin perform public.creator_review_verification(req,'approved','I approve myself'); exception when others then denied:=true; end;
 if not denied then raise exception 'Reviewer approved own account'; end if;
 perform set_config('request.jwt.claim.sub',cu::text,true);
 -- Biography changes preserve reviewed credentials; qualification changes invalidate them.
 row:=public.creator_save_profile(cp,details||'{"bio":"New biography"}');
 if row.verified_revision<>row.credential_revision then raise exception 'Biography revoked credentials'; end if;
 row:=public.creator_save_profile(cp,details||'{"qualifications":[{"name":"New certificate","issuer":"Different body","reference_url":""}]}');
 if row.verified_at is not null or row.credential_revision<>2 then raise exception 'Changed credentials kept verified mark'; end if;
 if not exists(select 1 from public.creator_verification_requests(cp) where status='superseded') then raise exception 'Old verification request not superseded'; end if;
 req:=public.creator_submit_verification(cp,'Review the new issuing body and qualification.',array[file]);
 perform set_config('request.jwt.claim.sub',au::text,true);
 perform public.creator_review_verification(req,'changes_requested','Please provide a current registry record.');
 perform set_config('request.jwt.claim.sub',cu::text,true);
 req:=public.creator_submit_verification(cp,'Here is an updated registry statement.',array[file]);
 perform set_config('request.jwt.claim.sub',au::text,true);
 perform public.creator_review_verification(req,'approved','Identity and new credentials checked against the register.');
 perform public.creator_review_verification(req,'revoked','Registration withdrawn by the issuing body.');
 if exists(select 1 from public.training_program_creators where id=cp and verified_at is not null) then raise exception 'Revoked mark visible'; end if;
 execute 'reset role';
 delete from private.creator_reviewers where user_id=au;
 execute 'set local role authenticated';
 denied:=false; begin perform public.creator_verification_requests(cp); exception when others then denied:=true; end;
 if not denied then raise exception 'Foreign verification request visible'; end if;
 if exists(select 1 from storage.objects where bucket_id='creator-evidence' and name=file) then raise exception 'Private evidence visible to non-reviewer'; end if;
 perform set_config('request.jwt.claim.sub',cu::text,true);
 row:=public.creator_save_profile(cp,details||'{"published":false}');
 perform set_config('request.jwt.claim.sub',au::text,true);
 if exists(select 1 from public.training_program_creators where id=cp) then raise exception 'Unpublished bio visible'; end if;
 if exists(select 1 from public.training_program_list_community() where id=programme and (creator_id is not null or credentials_verified)) then raise exception 'Unpublished creator still attributed'; end if;
 execute 'reset role';
 if has_function_privilege('anon','public.creator_save_profile(uuid,jsonb)','EXECUTE') or has_table_privilege('authenticated','private.creator_reviewers','INSERT') then raise exception 'Reviewer privilege leak'; end if;
end $$;
select 'Creator profile isolation, private evidence, reviewer authorization, self-verification denial, credential revision and revocation passed' as result;
rollback;
