-- Temporary two-account fixtures; no real plans or assignments are changed.
begin;
do $$
declare
  cf uuid; cu uuid; af uuid; au uuid; coach uuid; athlete uuid; other_profile uuid;
  programme uuid; version_id uuid; assignment uuid; pending_assignment uuid; replacement uuid;
  invitation public.training_program_client_connections; expired public.training_program_client_connections;
  content jsonb; plan jsonb; report jsonb; denied boolean;
begin
  select id,owner_user_id into cf,cu from public.families order by created_at limit 1;
  select id,owner_user_id into af,au from public.families where owner_user_id<>cu order by created_at limit 1;
  if af is null then raise exception 'Two account families required'; end if;
  content:='{"version":5,"activityTypes":[],"blocksByWeekday":{"Mon":[],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]},"program":{"schemaVersion":1,"name":"Direct clients fixture","description":"","startDate":"2026-10-05","completionMode":"repeat","phases":[{"id":"phase","name":"Build","focus":"","weeks":[{"id":"week","name":"Week 1","focus":"","blocksByWeekday":{"Mon":[],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]}}],"assessments":[]}]}}';
  insert into public.profiles(family_id,name,plan_json) values(cf,'Direct coach fixture',content) returning id into coach;
  insert into public.profiles(family_id,name,plan_json) values(af,'Direct athlete fixture',content) returning id into athlete;
  insert into public.profiles(family_id,name,plan_json) values(af,'Other athlete fixture',content) returning id into other_profile;
  perform set_config('request.jwt.claim.sub',cu::text,true);
  select s.program_id,s.version_id into programme,version_id from public.training_program_save(null,cf,coach,'Direct fixture','','','','all_levels','all_ages','{}','{}','community',content,'Initial') s;
  invitation:=public.training_program_invite_client(coach,'Direct coach',14);
  if not exists(select 1 from public.training_program_preview_client_invite(invitation.invite_token)) then raise exception 'Invite preview unavailable'; end if;
  denied:=false;
  begin perform public.training_program_accept_client_invite(invitation.invite_token,athlete); exception when others then denied:=true; end;
  if not denied then raise exception 'Coach accepted foreign profile'; end if;
  denied:=false;
  begin perform public.training_program_accept_client_invite(invitation.invite_token,coach); exception when others then denied:=true; end;
  if not denied then raise exception 'Own-family connection accepted'; end if;
  denied:=false;
  begin insert into public.training_program_assignments(program_id,version_id,assigned_by_family_id,target_profile_id,start_date) values(programme,version_id,cf,athlete,'2026-10-05'); exception when others then denied:=true; end;
  if not denied then raise exception 'Unconnected cross-account assignment created'; end if;
  execute 'set local role authenticated';
  perform set_config('request.jwt.claim.sub',au::text,true);
  if exists(select 1 from public.training_program_client_connections where id=invitation.id) then raise exception 'Foreign invitation tokens visible'; end if;
  if not exists(select 1 from public.training_program_preview_client_invite(invitation.invite_token)) then raise exception 'Capability preview failed'; end if;
  denied:=false;
  begin perform public.training_program_disconnect_client(invitation.id); exception when others then denied:=true; end;
  if not denied then raise exception 'Unconnected recipient revoked another coach invitation'; end if;
  perform public.training_program_accept_client_invite(invitation.invite_token,athlete);
  if not exists(select 1 from public.training_program_client_connections where id=invitation.id and client_profile_id=athlete and status='active') then raise exception 'Recipient connection not readable'; end if;
  if exists(select 1 from public.training_program_preview_client_invite(invitation.invite_token)) then raise exception 'Single-use preview still available'; end if;
  denied:=false;
  begin perform public.training_program_accept_client_invite(invitation.invite_token,other_profile); exception when others then denied:=true; end;
  if not denied then raise exception 'Invitation was reusable'; end if;
  perform set_config('request.jwt.claim.sub',cu::text,true);
  denied:=false;
  begin insert into public.training_program_assignments(program_id,version_id,assigned_by_family_id,target_profile_id,client_connection_id,start_date) values(programme,version_id,cf,other_profile,invitation.id,'2026-10-05'); exception when others then denied:=true; end;
  if not denied then raise exception 'Connection attached to wrong profile'; end if;
  if public.training_program_assign_clients(programme,array[invitation.id],'2026-10-05','repeat',false,false,'Follow supplied')<>1 then raise exception 'Direct assignment failed'; end if;
  if public.training_program_assign_clients(programme,array[invitation.id],'2026-10-05','repeat',false,false,'Duplicate')<>0 then raise exception 'Duplicate pending created'; end if;
  select id into assignment from public.training_program_assignments where client_connection_id=invitation.id and start_date='2026-10-05';
  perform set_config('request.jwt.claim.sub',au::text,true);
  denied:=false;
  begin perform public.training_program_accept_with_sharing(assignment,other_profile,'replace',null,false,false); exception when others then denied:=true; end;
  if not denied then raise exception 'Wrong sibling accepted direct assignment'; end if;
  plan:=public.training_program_accept_with_sharing(assignment,athlete,'replace',null,false,false);
  if plan #>> '{meta,activeProgramSource,recipientCanEdit}'<>'false' then raise exception 'Direct assignment lost follow permission'; end if;
  perform set_config('request.jwt.claim.sub',cu::text,true);
  report:=public.training_program_coach_report(assignment,current_date,28);
  if (report->>'adherenceShared')::boolean or report->'days'<>'[]' or report->'checkpoints'<>'[]' then raise exception 'Connection enabled private reporting'; end if;
  perform set_config('request.jwt.claim.sub',au::text,true);
  if not public.training_program_set_reporting(assignment,true,true) then raise exception 'Client reporting consent failed'; end if;
  perform set_config('request.jwt.claim.sub',cu::text,true);
  replacement:=public.training_program_offer_replacement(assignment,programme,'2026-10-12','repeat','Reschedule');
  if (select client_connection_id from public.training_program_assignments where id=replacement)<>invitation.id then raise exception 'Replacement lost connection'; end if;
  if public.training_program_assign_clients(programme,array[invitation.id],'2026-10-19','once',true,true,'Pending')<>1 then raise exception 'Additional invitation failed'; end if;
  select id into pending_assignment from public.training_program_assignments where client_connection_id=invitation.id and start_date='2026-10-19';
  perform set_config('request.jwt.claim.sub',au::text,true);
  if not public.training_program_disconnect_client(invitation.id) then raise exception 'Recipient disconnect failed'; end if;
  if (select plan_json from public.profiles where id=athlete)<>plan then raise exception 'Disconnect rewrote accepted plan'; end if;
  if not exists(select 1 from public.training_program_recipient_controls(athlete) where assignment_id=assignment) then raise exception 'Disconnect removed retained rights'; end if;
  denied:=false;
  begin perform public.training_program_accept_with_sharing(pending_assignment,athlete,'add',null,false,false); exception when others then denied:=true; end;
  if not denied then raise exception 'Revoked pending assignment accepted'; end if;
  perform set_config('request.jwt.claim.sub',cu::text,true);
  if exists(select 1 from public.training_program_assignments where client_connection_id=invitation.id and status='pending') then raise exception 'Pending assignments survived disconnect'; end if;
  denied:=false;
  begin perform public.training_program_coach_report(assignment,current_date,28); exception when others then denied:=true; end;
  if not denied then raise exception 'Disconnected coach still reported'; end if;
  denied:=false;
  begin perform public.training_program_offer_replacement(assignment,programme,'2026-10-26','repeat','After disconnect'); exception when others then denied:=true; end;
  if not denied then raise exception 'Disconnected coach still managed'; end if;
  denied:=false;
  begin perform public.training_program_assign_clients(programme,array[invitation.id],'2026-10-26','repeat',true,true,'After disconnect'); exception when others then denied:=true; end;
  if not denied then raise exception 'Disconnected coach still assigned'; end if;
  expired:=public.training_program_invite_client(coach,'Expiry coach',7);
  execute 'reset role';
  update public.training_program_client_connections set expires_at=now()-interval '1 day' where id=expired.id;
  execute 'set local role authenticated';
  perform set_config('request.jwt.claim.sub',au::text,true);
  denied:=false;
  begin perform public.training_program_accept_client_invite(expired.invite_token,athlete); exception when others then denied:=true; end;
  if not denied or exists(select 1 from public.training_program_preview_client_invite(expired.invite_token)) then raise exception 'Expired invitation available'; end if;
  execute 'reset role';
  if (select count(*) from public.training_program_notifications where client_connection_id=invitation.id)<>4 then raise exception 'Connection notifications missing'; end if;
  if has_function_privilege('anon','public.training_program_accept_client_invite(uuid,uuid)','execute') or has_table_privilege('authenticated','public.training_program_client_connections','INSERT') then raise exception 'Client permission leak'; end if;
end $$;
select 'Direct-client invitation consent, profile isolation, assignment permissions, replacement inheritance, disconnect and retained plans passed' as result;
rollback;
