// src/config/badges.js

// Trigger types for the generic BadgeEngine
export const BADGE_TRIGGER_TYPES = {
  SESSION_BEST_THRESHOLD: "SESSION_BEST_THRESHOLD", // best single session distance / speed
  STREAK_DAYS: "STREAK_DAYS",                      // consecutive active days
  DISTANCE_REPEAT: "DISTANCE_REPEAT",              // N sessions at ≥ X km
};

// Sports keys – keep in sync with cardioType values
export const SPORTS = {
  RUN: "run",
  BIKE: "bike",
  WALK: "walk",
  SWIM: "swim",
  ROW: "row",
};

// Core badge definitions.
// Repetition tiers use DISTANCE_REPEAT: distanceKm + requiredCount
// Speed badges use SESSION_BEST_THRESHOLD
// Streak badges use STREAK_DAYS
export const badgeDefinitions = [
  // ─────────────────────────────
  // RUN – 5K distance (repetition tiers)
  // ─────────────────────────────
  {
    id: "run_5k_bronze",
    family: "run_distance_5k",
    rarity: "bronze",
    title: "5K Runner – Bronze",
    description: "Completed a 5 km+ run once.",
    sport: SPORTS.RUN,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 5,
    requiredCount: 1,
    iconKey: "run_distance_5k",
    bgKey: "run_distance",
    xp: 25,
    sortOrder: 10,
  },
  {
    id: "run_5k_silver",
    family: "run_distance_5k",
    rarity: "silver",
    title: "5K Runner – Silver",
    description: "Completed a 5 km+ run 5 times.",
    sport: SPORTS.RUN,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 5,
    requiredCount: 5,
    iconKey: "run_distance_5k",
    bgKey: "run_distance",
    xp: 60,
    sortOrder: 11,
  },
  {
    id: "run_5k_gold",
    family: "run_distance_5k",
    rarity: "gold",
    title: "5K Runner – Gold",
    description: "Completed a 5 km+ run 20 times.",
    sport: SPORTS.RUN,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 5,
    requiredCount: 20,
    iconKey: "run_distance_5k",
    bgKey: "run_distance",
    xp: 150,
    sortOrder: 12,
  },

  // ─────────────────────────────
  // RUN – 10K distance (repetition tiers)
  // ─────────────────────────────
  {
    id: "run_10k_bronze",
    family: "run_distance_10k",
    rarity: "bronze",
    title: "10K Runner – Bronze",
    description: "Completed a 10 km+ run once.",
    sport: SPORTS.RUN,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 10,
    requiredCount: 1,
    iconKey: "run_distance_10k",
    bgKey: "run_distance",
    xp: 40,
    sortOrder: 20,
  },
  {
    id: "run_10k_silver",
    family: "run_distance_10k",
    rarity: "silver",
    title: "10K Runner – Silver",
    description: "Completed a 10 km+ run 5 times.",
    sport: SPORTS.RUN,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 10,
    requiredCount: 5,
    iconKey: "run_distance_10k",
    bgKey: "run_distance",
    xp: 90,
    sortOrder: 21,
  },
  {
    id: "run_10k_gold",
    family: "run_distance_10k",
    rarity: "gold",
    title: "10K Runner – Gold",
    description: "Completed a 10 km+ run 15 times.",
    sport: SPORTS.RUN,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 10,
    requiredCount: 15,
    iconKey: "run_distance_10k",
    bgKey: "run_distance",
    xp: 200,
    sortOrder: 22,
  },

  // ─────────────────────────────
  // BIKE – distance families (single-tier for now; you can add tiers later)
  // We use repetition-based logic so future tiers are easy to add.
  // ─────────────────────────────
  {
    id: "bike_20k_bronze",
    family: "bike_distance_20k",
    rarity: "bronze",
    title: "20K Rider",
    description: "Completed a 20 km+ ride once.",
    sport: SPORTS.BIKE,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 20,
    requiredCount: 1,
    iconKey: "bike_distance_20k",
    bgKey: "bike_distance",
    xp: 50,
    sortOrder: 40,
  },
  {
    id: "bike_50k_bronze",
    family: "bike_distance_50k",
    rarity: "silver",
    title: "50K Rider",
    description: "Completed a 50 km+ ride once.",
    sport: SPORTS.BIKE,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 50,
    requiredCount: 1,
    iconKey: "bike_distance_50k",
    bgKey: "bike_distance",
    xp: 100,
    sortOrder: 41,
  },
  {
    id: "bike_100k_bronze",
    family: "bike_distance_100k",
    rarity: "gold",
    title: "Century Rider",
    description: "Completed a 100 km+ ride once.",
    sport: SPORTS.BIKE,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 100,
    requiredCount: 1,
    iconKey: "bike_distance_100k",
    bgKey: "bike_distance",
    xp: 200,
    sortOrder: 42,
  },
  {
    id: "bike_200k_bronze",
    family: "bike_distance_200k",
    rarity: "mythic",
    title: "200K Rider",
    description: "Completed a 200 km+ ride once.",
    sport: SPORTS.BIKE,
    metricType: "distance",
    triggerType: BADGE_TRIGGER_TYPES.DISTANCE_REPEAT,
    distanceKm: 200,
    requiredCount: 1,
    iconKey: "bike_distance_200k",
    bgKey: "bike_distance",
    xp: 400,
    sortOrder: 43,
  },

  // ─────────────────────────────
  // RUNNING SPEED – best avg speed in any run
  // ─────────────────────────────
  {
    id: "run_speed_good",
    family: "speed_run",
    rarity: "bronze",
    title: "Quick Feet",
    description:
      "Hit an average running speed of 14 km/h or more in a single run.",
    sport: SPORTS.RUN,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 14,
    iconKey: "run_speed",
    bgKey: "run_speed",
    xp: 50,
    sortOrder: 60,
  },
  {
    id: "run_speed_great",
    family: "speed_run",
    rarity: "silver",
    title: "Fast Feet",
    description:
      "Hit an average running speed of 16 km/h or more in a single run.",
    sport: SPORTS.RUN,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 16,
    iconKey: "run_speed",
    bgKey: "run_speed",
    xp: 90,
    sortOrder: 61,
  },
  {
    id: "run_speed_outstanding",
    family: "speed_run",
    rarity: "gold",
    title: "Blazing Pace",
    description:
      "Hit an average running speed of 18 km/h or more in a single run.",
    sport: SPORTS.RUN,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 18,
    iconKey: "run_speed",
    bgKey: "run_speed",
    xp: 150,
    sortOrder: 62,
  },

  // ─────────────────────────────
  // CYCLING SPEED – best avg speed tiers (km/h equivalent of ~14–22 mph)
  // ─────────────────────────────
  {
    id: "bike_speed_good",
    family: "speed_bike",
    rarity: "bronze",
    title: "Solid Spinner",
    description:
      "Hit an average cycling speed of 22.5 km/h (14 mph) or more in a ride.",
    sport: SPORTS.BIKE,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 22.5,
    iconKey: "bike_speed",
    bgKey: "bike_speed",
    xp: 60,
    sortOrder: 70,
  },
  {
    id: "bike_speed_great",
    family: "speed_bike",
    rarity: "silver",
    title: "Strong Spinner",
    description:
      "Hit an average cycling speed of 26 km/h (16 mph) or more in a ride.",
    sport: SPORTS.BIKE,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 26,
    iconKey: "bike_speed",
    bgKey: "bike_speed",
    xp: 100,
    sortOrder: 71,
  },
  {
    id: "bike_speed_outstanding",
    family: "speed_bike",
    rarity: "gold",
    title: "Speed Machine",
    description:
      "Hit an average cycling speed of 29 km/h (18 mph) or more in a ride.",
    sport: SPORTS.BIKE,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 29,
    iconKey: "bike_speed",
    bgKey: "bike_speed",
    xp: 150,
    sortOrder: 72,
  },
  {
    id: "bike_speed_pro",
    family: "speed_bike",
    rarity: "platinum",
    title: "Pro Pace",
    description:
      "Hit an average cycling speed of 32 km/h (20 mph) or more in a ride.",
    sport: SPORTS.BIKE,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 32,
    iconKey: "bike_speed",
    bgKey: "bike_speed",
    xp: 200,
    sortOrder: 73,
  },
  {
    id: "bike_speed_elite",
    family: "speed_bike",
    rarity: "diamond",
    title: "Elite Pace",
    description:
      "Hit an average cycling speed of 35 km/h (22 mph) or more in a ride.",
    sport: SPORTS.BIKE,
    metricType: "speed",
    triggerType: BADGE_TRIGGER_TYPES.SESSION_BEST_THRESHOLD,
    metric: "bestAvgSpeedBySport",
    threshold: 35,
    iconKey: "bike_speed",
    bgKey: "bike_speed",
    xp: 260,
    sortOrder: 74,
  },

  // ─────────────────────────────
  // STREAK BADGES – Fortnite / Rocket League style naming
  // ─────────────────────────────
  {
    id: "streak_3",
    family: "consistency",
    rarity: "bronze",
    title: "3-Day Streak",
    description: "Trained 3 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 3,
    iconKey: "streak",
    bgKey: "streak",
    xp: 15,
    sortOrder: 100,
  },
  {
    id: "streak_7",
    family: "consistency",
    rarity: "silver",
    title: "7-Day Streak",
    description: "Trained 7 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 7,
    iconKey: "streak",
    bgKey: "streak",
    xp: 40,
    sortOrder: 101,
  },
  {
    id: "streak_14",
    family: "consistency",
    rarity: "gold",
    title: "14-Day Streak",
    description: "Trained 14 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 14,
    iconKey: "streak",
    bgKey: "streak",
    xp: 80,
    sortOrder: 102,
  },
  {
    id: "streak_30",
    family: "consistency",
    rarity: "platinum",
    title: "30-Day Streak",
    description: "Trained 30 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 30,
    iconKey: "streak",
    bgKey: "streak",
    xp: 150,
    sortOrder: 103,
  },
  {
    id: "streak_60",
    family: "consistency",
    rarity: "diamond",
    title: "60-Day Streak",
    description: "Trained 60 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 60,
    iconKey: "streak",
    bgKey: "streak",
    xp: 250,
    sortOrder: 104,
  },
  {
    id: "streak_90_mythic",
    family: "consistency",
    rarity: "mythic",
    title: "Mythic Streak",
    description: "Trained 90 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 90,
    iconKey: "streak",
    bgKey: "streak",
    xp: 400,
    sortOrder: 105,
  },
  {
    id: "streak_180_ssl",
    family: "consistency",
    rarity: "ssl",
    title: "Super Sonic Legend",
    description: "Trained 180 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 180,
    iconKey: "streak",
    bgKey: "streak",
    xp: 800,
    sortOrder: 106,
  },
  {
    id: "streak_365_unreal",
    family: "consistency",
    rarity: "unreal",
    title: "Unreal Streak",
    description: "Trained 365 days in a row.",
    metricType: "streak",
    triggerType: BADGE_TRIGGER_TYPES.STREAK_DAYS,
    threshold: 365,
    iconKey: "streak",
    bgKey: "streak",
    xp: 1500,
    sortOrder: 107,
  },
];
