// src/config/runBadgesV1.js

// V1 running distance badges used by the main stacked plaques UI.
// This file just holds data; all logic/UX remains in App.jsx.

export const BADGE_DEFS = [
  {
    key: "badge_run_5k_1",
    title: "5K Run",
    desc: "Logged 5K+ runs",
    category: "running",
    tier: "bronze",
    distanceLabel: "5K",
    bg: "/badges/bg/bg_running_bronze.svg",
    icon: "/badges/icons/icon_runner_5k.png",
    emoji: "🏅",
    xp: 25,
    hidden: true, // keep for logic but don’t render
  },
  {
    key: "badge_run_5k_2",
    title: "5K Run",
    desc: "Logged 5K+ runs",
    category: "running",
    tier: "silver",
    distanceLabel: "5K",
    bg: "/badges/bg/bg_running_silver.svg",
    icon: "/badges/icons/icon_runner_5k.png",
    emoji: "🥈",
    xp: 35,
    hidden: true,
  },
  {
    key: "badge_run_5k_3",
    title: "5K Run",
    desc: "Logged 5K+ runs",
    category: "running",
    tier: "gold",
    distanceLabel: "5K",
    bg: "/badges/bg/bg_running_gold.svg",
    icon: "/badges/icons/icon_runner_5k.png",
    emoji: "🥇",
    xp: 45,
  },
  {
    key: "badge_run_5k_4",
    title: "5K Run",
    desc: "Logged 5K+ runs",
    category: "running",
    tier: "platinum",
    distanceLabel: "5K",
    bg: "/badges/bg/bg_running_platinum.svg",
    icon: "/badges/icons/icon_runner_5k.png",
    emoji: "💠",
    xp: 60,
    hidden: true,
  },
  {
    key: "badge_run_5k_5",
    title: "5K Run",
    desc: "Logged 5K+ runs",
    category: "running",
    tier: "diamond",
    distanceLabel: "5K",
    bg: "/badges/bg/bg_running_diamond.svg",
    icon: "/badges/icons/icon_runner_5k.png",
    emoji: "💎",
    xp: 80,
    hidden: true,
  },
  {
    key: "badge_run_10k_1",
    title: "10K Run",
    desc: "Logged 10K+ runs",
    category: "running",
    tier: "bronze",
    distanceLabel: "10K",
    bg: "/badges/bg/bg_running_bronze.svg",
    icon: "/badges/icons/icon_runner_10k.png",
    emoji: "🏆",
    xp: 50,
  },
  {
    key: "badge_run_10k_2",
    title: "10K Run",
    desc: "Logged 10K+ runs",
    category: "running",
    tier: "silver",
    distanceLabel: "10K",
    bg: "/badges/bg/bg_running_silver.svg",
    icon: "/badges/icons/icon_runner_10k.png",
    emoji: "🏆",
    xp: 65,
    hidden: true,
  },
  {
    key: "badge_run_10k_3",
    title: "10K Run",
    desc: "Logged 10K+ runs",
    category: "running",
    tier: "gold",
    distanceLabel: "10K",
    bg: "/badges/bg/bg_running_gold.svg",
    icon: "/badges/icons/icon_runner_10k.png",
    emoji: "🏆",
    xp: 80,
    hidden: true,
  },
  {
    key: "badge_run_10k_4",
    title: "10K Run",
    desc: "Logged 10K+ runs",
    category: "running",
    tier: "platinum",
    distanceLabel: "10K",
    bg: "/badges/bg/bg_running_platinum.svg",
    icon: "/badges/icons/icon_runner_10k.png",
    emoji: "🏆",
    xp: 100,
    hidden: true,
  },
  {
    key: "badge_run_10k_5",
    title: "10K Run",
    desc: "Logged 10K+ runs",
    category: "running",
    tier: "diamond",
    distanceLabel: "10K",
    bg: "/badges/bg/bg_running_diamond.svg",
    icon: "/badges/icons/icon_runner_10k.png",
    emoji: "🏆",
    xp: 130,
    hidden: true,
  },
];

export const RUN_5K_TIERS = [
  { key: "badge_run_5k_1", tier: "bronze",   threshold: 1,  xp: 25 },
  { key: "badge_run_5k_2", tier: "silver",   threshold: 3,  xp: 35 },
  { key: "badge_run_5k_3", tier: "gold",     threshold: 5,  xp: 45 },
  { key: "badge_run_5k_4", tier: "platinum", threshold: 10, xp: 60 },
  { key: "badge_run_5k_5", tier: "diamond",  threshold: 25, xp: 80 },
];

export const RUN_10K_TIERS = [
  { key: "badge_run_10k_1", tier: "bronze",   threshold: 1,  xp: 50 },
  { key: "badge_run_10k_2", tier: "silver",   threshold: 3,  xp: 65 },
  { key: "badge_run_10k_3", tier: "gold",     threshold: 5,  xp: 80 },
  { key: "badge_run_10k_4", tier: "platinum", threshold: 10, xp: 100 },
  { key: "badge_run_10k_5", tier: "diamond",  threshold: 25, xp: 130 },
];

export const RUNNING_BADGE_KEYS = new Set([
  ...RUN_5K_TIERS.map((t) => t.key),
  ...RUN_10K_TIERS.map((t) => t.key),
]);